# Public SDK entry points are kept for app integrations, reflective setup, and stack traces.
-keep class com.apm.** { public *; }

# Slow-method ASM instrumentation calls these static methods by generated bytecode.
-keep class com.apm.slowmethod.ApmSlowMethodTracer {
    public static void methodEnter(java.lang.String);
    public static void methodExit(java.lang.String);
}

# JNI entry points in crash, memory dump, and IO modules must keep native method names.
-keepclasseswithmembers class com.apm.** {
    native <methods>;
}

# Optional integrations are compileOnly and provided by host apps when enabled.
-dontwarn io.opentelemetry.**
-dontwarn okhttp3.**
